### ISSUE TITLE
Question on sample points length

### ISSUE THREAD

**Issue by akatav** [taspinar/siml#2]
Great code! very useful, thank you. 
i have a question. i am trying to adopt this sort of method to analyse my resting EEG data of MCI vs normal patients.These are .set files where for each individual who was examined, each channel (there are totally 19 electrodes placed), the sample points are varying in length. How is this sort of a problem addressed where for an individual, we have a n_channels*n_times where n_times is different for each individual.

**Comment by taspinar** [comment]
I guess these are two seperate questions:
1. How should N different channels be handled? 
2. How should M different samples (each with N channels but varying recording time) be handled?

For 1 i would say that each channel should be processed independently. Meaning that N different channels will produce N*K features assuming each channel produces K features.
For question 2 it really depends on *how* varied the sample lengths are. You could split each sample into subsamples of the same length. These subsamples could be overlapping or not.

**Comment by akatav** [comment]
@taspinar thank you so much! i think in signal processing, samples mean the sampling points per signal(related to sampling frequency) as opposed to samples, conventionally used in ML to mean number of data points.that is the main source of confusion :)
so, each one of the .set files belongs to each individual that was tested. Every .set file has different n_times (sampling points) but the same number of channels (n_channels), of course. Is there an example of processing this type of EEG file(s) in python?

**Comment by akatav** [comment]
thank you.
