### ISSUE TITLE
"ValueError: not enough values to unpack (expected 4, got 2)"

### ISSUE THREAD

**Issue by bemoregt** [taspinar/siml#5]
HI, @taspinar 

I met this error when run your scalogram ipynb.
at Third block: 3. Plot the Scaleogram using the Continuous Wavelet Transform 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-f981d74de776> in <module>
     29 
     30 fig, ax = plt.subplots(figsize=(10, 10))
---> 31 plot_wavelet(ax, time, signal, scales, xlabel=xlabel, ylabel=ylabel, title=title)
     32 plt.show()

<ipython-input-5-f981d74de776> in plot_wavelet(ax, time, signal, scales, waveletname, cmap, title, ylabel, xlabel)
      3 
      4     dt = time[1] - time[0]
----> 5     [coefficients, frequencies,_,_] = pywt.cwt(signal, scales, waveletname, dt)
      6     power = (abs(coefficients)) ** 2
      7     period = 1. / frequencies

"ValueError: not enough values to unpack (expected 4, got 2)"

Whats wrong to me ?

Thanks.
Best,
@bemoregt.

**Comment by taspinar** [comment]
@bemoregt 
pywt.cwt() does indeed return 2 objects instead of 4. Previously I was using a local version of pywt which return 4 objects. I though I had updated this error everywhere, but appearantly not in this notebook. 
It should be correct now.
